spring:
  datasource:
    url: jdbc:mysql://root:WWyLeQgCcuTzLhVqNurWwizbApnvnhgF@interchange.proxy.rlwy.net:39544/study
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: WWyLeQgCcuTzLhVqNurWwizbApnvnhgF
    username: root
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 210142505443-uisnk00vc1kcd6sk630o0pe68i52866u.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/home

server:
  port: ${PORT:8080}
jwt:
  signerKey : "hvsA/0Yr+0dOL4fQkEmVLgUeJgnsufJB8+nzFOd99MUo10wvoTUf3/krYa9TEtDC"


