spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/study}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_USERNAME:root}
    username: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 210142505443-uisnk00vc1kcd6sk630o0pe68i52866u.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/home

server:
  port: 8080
jwt:
  signerKey : "hvsA/0Yr+0dOL4fQkEmVLgUeJgnsufJB8+nzFOd99MUo10wvoTUf3/krYa9TEtDC"


